"""card bank code

Revision ID: 1224a03314ae
Revises: 254a5d629246
Create Date: 2026-07-20 13:06:22.743409
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1224a03314ae"
down_revision: str | None = "254a5d629246"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cards", sa.Column("bank_code", sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cards", "bank_code")
    # ### end Alembic commands ###
