"""cards, invoices, notifications and b2b

Revision ID: 254a5d629246
Revises: 2687fb3db1a8
Create Date: 2026-07-20 12:55:33.255410
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "254a5d629246"
down_revision: str | None = "2687fb3db1a8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "b2b_payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "SUCCESS",
                "FAILED",
                name="b2bstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("bulk_id", sa.String(length=32), nullable=True),
        sa.Column("payee_iban", sa.String(length=34), nullable=False),
        sa.Column("payee_name", sa.String(length=255), nullable=False),
        sa.Column("payee_tin", sa.String(length=16), nullable=False),
        sa.Column("bank_code", sa.String(length=16), nullable=False),
        sa.Column("bank_name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("address", sa.String(length=512), nullable=True),
        sa.Column("additional_info", sa.Text(), nullable=True),
        sa.Column("bulk_description", sa.Text(), nullable=True),
        sa.Column("webhook_url", sa.String(length=512), nullable=True),
        sa.Column("webhook_sent", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_b2b_payments_merchant_id"), "b2b_payments", ["merchant_id"], unique=False
    )
    op.create_index(op.f("ix_b2b_payments_order_id"), "b2b_payments", ["order_id"], unique=False)
    op.create_index(op.f("ix_b2b_payments_trace_id"), "b2b_payments", ["trace_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("recipient", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_invoice_id"), "notifications", ["invoice_id"], unique=False
    )
    op.create_index(op.f("ix_notifications_trace_id"), "notifications", ["trace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notifications_trace_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_invoice_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_b2b_payments_trace_id"), table_name="b2b_payments")
    op.drop_index(op.f("ix_b2b_payments_order_id"), table_name="b2b_payments")
    op.drop_index(op.f("ix_b2b_payments_merchant_id"), table_name="b2b_payments")
    op.drop_table("b2b_payments")
    # ### end Alembic commands ###
