"""initial schema

Revision ID: 2687fb3db1a8
Revises:
Create Date: 2026-07-20 11:23:19.569856
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2687fb3db1a8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_key", sa.String(length=32), nullable=False),
        sa.Column("private_key", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("tin", sa.String(length=16), nullable=True),
        sa.Column("contact_phone", sa.String(length=32), nullable=True),
        sa.Column("site_url", sa.String(length=512), nullable=True),
        sa.Column("result_url", sa.String(length=512), nullable=True),
        sa.Column("success_url", sa.String(length=512), nullable=True),
        sa.Column("error_url", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_merchants_public_key"), "merchants", ["public_key"], unique=True)
    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.String(length=32), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=False),
        sa.Column("mask", sa.String(length=24), nullable=False),
        sa.Column("holder_name", sa.String(length=255), nullable=True),
        sa.Column("expiry", sa.String(length=5), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "active",
                "pending",
                "rejected",
                "expired",
                "session_expired",
                name="cardstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_payout_card", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cards_card_id"), "cards", ["card_id"], unique=True)
    op.create_index(op.f("ix_cards_merchant_id"), "cards", ["merchant_id"], unique=False)
    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "waiting_for_payment",
                "paid",
                "canceled",
                name="invoicestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("display", sa.Boolean(), nullable=False),
        sa.Column("save_as_template", sa.Boolean(), nullable=False),
        sa.Column("allow_installment", sa.Boolean(), nullable=False),
        sa.Column("recipient_name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("tin", sa.String(length=16), nullable=True),
        sa.Column("contract_number", sa.String(length=64), nullable=True),
        sa.Column("merchant_order_id", sa.String(length=255), nullable=True),
        sa.Column("period_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoices_merchant_id"), "invoices", ["merchant_id"], unique=False)
    op.create_table(
        "request_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=True),
        sa.Column("method", sa.String(length=8), nullable=False),
        sa.Column("path", sa.String(length=255), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("raw_data", sa.Text(), nullable=True),
        sa.Column("raw_signature", sa.String(length=64), nullable=True),
        sa.Column("signature_valid", sa.Boolean(), nullable=True),
        sa.Column("request_payload", sa.JSON(), nullable=True),
        sa.Column("response_payload", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_request_logs_merchant_id"), "request_logs", ["merchant_id"], unique=False
    )
    op.create_index(op.f("ix_request_logs_path"), "request_logs", ["path"], unique=False)
    op.create_index(op.f("ix_request_logs_trace_id"), "request_logs", ["trace_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.String(length=32), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "success",
                "failed",
                "error",
                "returned",
                "server_error",
                name="transactionstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("bank_code", sa.String(length=8), nullable=True),
        sa.Column("message", sa.String(length=255), nullable=True),
        sa.Column("operation_code", sa.String(length=8), nullable=True),
        sa.Column("bank_transaction", sa.String(length=32), nullable=True),
        sa.Column("rrn", sa.String(length=16), nullable=True),
        sa.Column("card_mask", sa.String(length=24), nullable=True),
        sa.Column("card_name", sa.String(length=255), nullable=True),
        sa.Column("endpoint", sa.String(length=64), nullable=False),
        sa.Column("checkout_token", sa.String(length=64), nullable=True),
        sa.Column("success_redirect_url", sa.String(length=512), nullable=True),
        sa.Column("error_redirect_url", sa.String(length=512), nullable=True),
        sa.Column("other_attr", sa.JSON(), nullable=True),
        sa.Column("card_id", sa.Integer(), nullable=True),
        sa.Column("split_merchant_id", sa.Integer(), nullable=True),
        sa.Column("split_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["split_merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("checkout_token"),
    )
    op.create_index(
        op.f("ix_transactions_merchant_id"), "transactions", ["merchant_id"], unique=False
    )
    op.create_index(
        "ix_transactions_merchant_order", "transactions", ["merchant_id", "order_id"], unique=False
    )
    op.create_index(op.f("ix_transactions_order_id"), "transactions", ["order_id"], unique=False)
    op.create_index(op.f("ix_transactions_trace_id"), "transactions", ["trace_id"], unique=False)
    op.create_index(
        op.f("ix_transactions_transaction_id"), "transactions", ["transaction_id"], unique=True
    )
    op.create_table(
        "balance_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_balance_entries_merchant_id"), "balance_entries", ["merchant_id"], unique=False
    )
    op.create_index(
        op.f("ix_balance_entries_transaction_id"),
        "balance_entries",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "callbacks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("target_url", sa.String(length=512), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "delivered",
                "failed",
                "dropped",
                name="callbackstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("payload_data", sa.Text(), nullable=False),
        sa.Column("payload_signature", sa.String(length=64), nullable=False),
        sa.Column("decoded_payload", sa.JSON(), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_callbacks_transaction_id"), "callbacks", ["transaction_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_callbacks_transaction_id"), table_name="callbacks")
    op.drop_table("callbacks")
    op.drop_index(op.f("ix_balance_entries_transaction_id"), table_name="balance_entries")
    op.drop_index(op.f("ix_balance_entries_merchant_id"), table_name="balance_entries")
    op.drop_table("balance_entries")
    op.drop_index(op.f("ix_transactions_transaction_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_trace_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_order_id"), table_name="transactions")
    op.drop_index("ix_transactions_merchant_order", table_name="transactions")
    op.drop_index(op.f("ix_transactions_merchant_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_request_logs_trace_id"), table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_path"), table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_merchant_id"), table_name="request_logs")
    op.drop_table("request_logs")
    op.drop_index(op.f("ix_invoices_merchant_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_cards_merchant_id"), table_name="cards")
    op.drop_index(op.f("ix_cards_card_id"), table_name="cards")
    op.drop_table("cards")
    op.drop_index(op.f("ix_merchants_public_key"), table_name="merchants")
    op.drop_table("merchants")
    # ### end Alembic commands ###
