"""merchant feature grants

Revision ID: aa0f8d525bdb
Revises: 1224a03314ae
Create Date: 2026-07-20 14:07:26.105877
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "aa0f8d525bdb"
down_revision: str | None = "1224a03314ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "merchants",
        sa.Column("amex_enabled", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("merchants", "amex_enabled", server_default=None)
    op.add_column(
        "merchants",
        sa.Column(
            "token_payments_enabled", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.alter_column("merchants", "token_payments_enabled", server_default=None)
    op.add_column(
        "merchants",
        sa.Column("installments_enabled", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("merchants", "installments_enabled", server_default=None)
    op.add_column(
        "merchants",
        sa.Column("wallets_enabled", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("merchants", "wallets_enabled", server_default=None)
    op.add_column(
        "merchants",
        sa.Column("b2b_enabled", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("merchants", "b2b_enabled", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("merchants", "b2b_enabled")
    op.drop_column("merchants", "wallets_enabled")
    op.drop_column("merchants", "installments_enabled")
    op.drop_column("merchants", "token_payments_enabled")
    op.drop_column("merchants", "amex_enabled")
    # ### end Alembic commands ###
